driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.10
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[maradns::default]
